"""empty message

Revision ID: 31e0a223da87
Revises: b16c3a0f3408
Create Date: 2020-11-20 18:18:28.002335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e0a223da87'
down_revision = 'b16c3a0f3408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(), nullable=True))

    op.execute('UPDATE venues SET seeking_talent = True;')

    op.alter_column('venues', 'seeking_talent', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'seeking_description')
    # ### end Alembic commands ###
