"""empty message

Revision ID: 4f4b061c9f47
Revises: 6a9f578676cf
Create Date: 2020-11-20 00:32:14.424133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4b061c9f47'
down_revision = '6a9f578676cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
