"""empty message

Revision ID: 835538cbf37f
Revises: 31e0a223da87
Create Date: 2020-11-20 18:41:20.194424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835538cbf37f'
down_revision = '31e0a223da87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('website', sa.String(), nullable=True))

    op.execute('UPDATE artists SET seeking_venues = True;')

    op.alter_column('artists', 'seeking_venues', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website')
    op.drop_column('artists', 'seeking_venues')
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
