"""empty message

Revision ID: 8494a48fbd9d
Revises: 8990ba537eaa
Create Date: 2020-11-18 22:34:39.171828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8494a48fbd9d'
down_revision = '8990ba537eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
